export const columns = [
  // accessor serves as a column key, which is used to define each column in row data
  {
    Header: 'DC',
    accessor: 'DC',
  },
  {
    Header: 'Vendor',
    accessor: 'Vendor',
  },
  {
    Header: 'Group',
    accessor: 'Group',
  },
  {
    Header: 'Host Name',
    accessor: 'Host Name',
  },
  {
    Header: 'Nagios Status',
    accessor: 'Nagios Status',
  },
  {
    Header: 'Warranty',
    accessor: 'Warranty',
  },
  {
    Header: 'Priority',
    accessor: 'Priority',
  },
  {
    Header: 'Ticket Number',
    accessor: 'Ticket Number',
  },
  {
    Header: 'Ticket Title',
    accessor: 'Ticket Title',
  },
  {
    Header: 'Date Open',
    accessor: 'Date Open',
  },
  {
    Header: 'Issue',
    accessor: 'Issue',
  },
  {
    Header: 'RMA Number',
    accessor: 'RMA Number',
  },
  {
    Header: 'Work Order',
    accessor: 'Work Order',
  },
  {
    Header: 'WO Status',
    accessor: 'WO Status',
  },
  {
    Header: 'Ticket Status',
    accessor: 'Ticket Status',
  },
  {
    Header: 'Escalate',
    accessor: 'Escalate',
  },
  {
    Header: 'Request By',
    accessor: 'Request By',
  },
  {
    Header: 'Incoming Tracking',
    accessor: 'Incoming Tracking',
  },
  {
    Header: 'Outgoing Tracking',
    accessor: 'Outgoing Tracking',
  },
];

export const data = [
  {
    "DC": "DC",
    "Vendor": "Vendor",
    "Group": "Group",
    "Hostname": "Hostname",
    "Nagios Status": "Nagios_status",
    "Warranty": "Warranty",
    "Priority": "Priority",
    "Ticket Number": "Ticket#",
    "Ticket Title": "Ticket_title",
    "Date Open": "Ticket_open_date",
    "Issue": "Issue",
    "RMA Number": "RMA#",
    "Work Order": "WO#",
    "WO Status": "WO_status",
    "Ticket Status": "Ticket_status",
    "Escalate": "Escalate",
    "Request By": "Request By",
    "Incoming Tracking": "Incoming Tracking",
    "Outgoing Tracking": "Outgoing Tracking",
  },
  {
    "DC": "PV",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "pv42p49im-filerm49008",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076471776",
    "Ticket Title": "iTicket- : PAMFLT on slot 3 on pv42p49im-filerm49008",
    "Date Open": "44081.69099537037",
    "Issue": "Memory Failure",
    "RMA Number": "N/A",
    "Work Order": "NONE",
    "WO Status": "Work",
    "Ticket Status": "ISG Mail Storage",
    "Escalate": "Mohit Modi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MR",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "mr29p50im-filerm50011",
    "Nagios Status": "production",
    "Warranty": "YES",
    "Priority": "2",
    "Ticket Number": "INC076440551",
    "Ticket Title": "iTicket- : Please perform visual inspection on mr29p50im-filerm50011, shelf 20 module B failed",
    "Date Open": "44077.90488425926",
    "Issue": "GPU Failure",
    "RMA Number": "need_RMA",
    "Work Order": "WO000208327",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Umakant Tripathi",
    "Request By": "need_tracking",
    "Incoming Tracking": "need_tracking",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MR",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "mr84p72im-ztdj08031701",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076439860",
    "Ticket Title": "iTicket- : System down mr84p72im-ztdj08031701",
    "Date Open": "44077.85141203704",
    "Issue": "Inspect Device",
    "RMA Number": "N/A",
    "Work Order": "WO000208271",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "ST",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "st13p97im-ztdj18302201",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076421449",
    "Ticket Title": "iTicket- : /dev/sdg disk has failed on st13p97im-ztdj18302201 node. Replace with onsite spare",
    "Date Open": "44076.51530092592",
    "Issue": "Data Drive Failure",
    "RMA Number": "N/A",
    "Work Order": "WO000207686",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "ISG Mail Storage",
    "Escalate": "Vinodkumar Chirumamilla",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "NK",
    "Vendor": "NetApp",
    "Group": "iCloud",
    "Hostname": "nk11p00mm-fileradminm002",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076408408",
    "Ticket Title": "iTicket- : SP and console not reachable for nk11p00mm-fileradminm002, please perform visual inspection",
    "Date Open": "44075.43960648148",
    "Issue": "Inspect Device",
    "RMA Number": "N/A",
    "Work Order": "WO000207386|||||WO000208041",
    "WO Status": "Pending Validation",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Rishav Kumar",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "PV",
    "Vendor": "Isilon",
    "Group": "iCloud",
    "Hostname": "pv37p00ce-isi01-04",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076365843",
    "Ticket Title": "iTicket- : Replace faulty DIMM on pv37p00ce-isi01-04",
    "Date Open": "44070.644467592596",
    "Issue": "Inspect Device",
    "RMA Number": "N/A",
    "Work Order": "NONE",
    "WO Status": "Escalate",
    "Ticket Status": "ISG Mail Storage",
    "Escalate": "Rishav Kumar",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "NK",
    "Vendor": "NetApp",
    "Group": "iCloud",
    "Hostname": "nk11p00me-filer001",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076362503",
    "Ticket Title": "iTicket- : Console is not working nk11p00me-filer001/2 Please do visual inspection",
    "Date Open": "44070.29099537037",
    "Issue": "Inspect Device",
    "RMA Number": "N/A",
    "Work Order": "WO000205796",
    "WO Status": "Work",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Anil Kumar Rajak",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MR",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "mr85p72im-hygn05151601",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076355487",
    "Ticket Title": "iTicket- : Failed disk /dev/sdh on mr85p72im-hygn05151601 node. replace with onsite spare",
    "Date Open": "44069.70280092592",
    "Issue": "Data Drive Failure",
    "RMA Number": "N/A",
    "Work Order": "WO000205569",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "ISG Mail Storage",
    "Escalate": "Vinodkumar Chirumamilla",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "ST",
    "Vendor": "Cisco",
    "Group": "iCloud_Mail",
    "Hostname": "st13p21im-cs21551",
    "Nagios Status": "non-production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076232782",
    "Ticket Title": "iTicket- : Console unreachable on Datahall 204",
    "Date Open": "44056.238217592596",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000200967",
    "WO Status": "Work",
    "Ticket Status": "ISG Mail Storage",
    "Escalate": "Mohit Modi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MR",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "mr84p72im-ztdj08023301",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076223134",
    "Ticket Title": "iTicket- : sdb failed on mr84p72im-ztdj08023301please replace with onsite spare",
    "Date Open": "44055.20905092593",
    "Issue": "Data Drive Failure",
    "RMA Number": "N/A",
    "Work Order": "WO000200476",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Kavitha Paulraj",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MR",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "mr36p72im-hygi09034101",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076223027",
    "Ticket Title": "iTicket- : /dev/sdg failed pls replace with onsite spare",
    "Date Open": "44055.199328703704",
    "Issue": "Data Drive Failure",
    "RMA Number": "N/A",
    "Work Order": "WO000200471",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Kavitha Paulraj",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "ST",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "st42p63im-ztfp17230101",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076222604",
    "Ticket Title": "iTicket- : /dev/sdc has failed on st42p63im-ztfp17230101 node. Replace with onsite spare",
    "Date Open": "44055.18127314815",
    "Issue": "Data Drive Failure",
    "RMA Number": "N/A",
    "Work Order": "WO000200467",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "ISG Mail Storage",
    "Escalate": "Vinodkumar Chirumamilla",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "ST",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "st42p63im-ztfp17240501",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076222451",
    "Ticket Title": "iTicket- : /dev/sdc has failed on st42p63im-ztfp17240501 node. Replace with onsite spare",
    "Date Open": "44055.16946759259",
    "Issue": "Data Drive Failure",
    "RMA Number": "N/A",
    "Work Order": "WO000200464",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "ISG Mail Storage",
    "Escalate": "Vinodkumar Chirumamilla",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "PV",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "pv48p67im-ztfp05040801",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076222293",
    "Ticket Title": "iTicket- : /dev/sde disk has failed on pv48p67im-ztfp05040801 node. Replace with onsite spare",
    "Date Open": "44055.15210648148",
    "Issue": "Data Drive Failure",
    "RMA Number": "N/A",
    "Work Order": "WO000200452",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "ISG Mail Storage",
    "Escalate": "Vinodkumar Chirumamilla",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MR",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "mr36p72im-hygi09051001",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076222216",
    "Ticket Title": "iTicket- : /dev/sdc disk has failed on mr36p72im-hygi09051001 node. replace with onsite spare",
    "Date Open": "44055.14099537037",
    "Issue": "Data Drive Failure",
    "RMA Number": "N/A",
    "Work Order": "WO000200447",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "ISG Mail Storage",
    "Escalate": "Vinodkumar Chirumamilla",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "PV",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "pv41p18im-filerm18562",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076212713",
    "Ticket Title": "iTicket- : ps4 failed on shelf 21 on pv41p18im-filerm18562",
    "Date Open": "44054.15974537037",
    "Issue": "Power Supply Failure",
    "RMA Number": "N/A",
    "Work Order": "INC076343086|||||WO000199987",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Kavitha Paulraj",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MR",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "mr84p72im-ztdj09023201",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076208484",
    "Ticket Title": "iTicket- : Host mr84p72im-ztdj09023201 is not reachable, pls have visual check",
    "Date Open": "44053.73474537037",
    "Issue": "Host Unreachable",
    "RMA Number": "N/A",
    "Work Order": "WO000199803",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Umakant Tripathi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "PV",
    "Vendor": "Avere",
    "Group": "AMP",
    "Hostname": "pv39p00it-averecl002",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076194727",
    "Ticket Title": "iTicket- : Possible networking issue on pv39p00it-averecl002 b/w 1-2AM PDT 8/8",
    "Date Open": "44051.78613425926",
    "Issue": "Inspect Device",
    "RMA Number": "N/A",
    "Work Order": "NONE",
    "WO Status": "Work",
    "Ticket Status": "ISG Mail Storage",
    "Escalate": "Mohit Modi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "ST",
    "Vendor": "Silver Peak",
    "Group": "iCloud_Mail",
    "Hostname": "st13p27im-wam006",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076192750",
    "Ticket Title": "iTicket- : Failed disk on slot 16 on st13p27im-wam006",
    "Date Open": "44051.502800925926",
    "Issue": "Data Drive Failure",
    "RMA Number": "N/A",
    "Work Order": "WO000204689",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "ISG Mail Storage",
    "Escalate": "Manoj Annamalai",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "PV",
    "Vendor": "Silver Peak",
    "Group": "iCloud_Mail",
    "Hostname": "pv36p47im-wam006",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076144363",
    "Ticket Title": "iTicket- : Slot 1 - Disk is degraded on wam pv36p47im-wam006. please replace with onsite spare",
    "Date Open": "44047.13752314815",
    "Issue": "Data Drive Failure",
    "RMA Number": "N/A",
    "Work Order": "WO000197688",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "ISG Mail Storage",
    "Escalate": "Vinodkumar Chirumamilla",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MS",
    "Vendor": "NetApp",
    "Group": "iCloud",
    "Hostname": "ms11q11im-filerm01101",
    "Nagios Status": "non-production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC076068554",
    "Ticket Title": "iTicket- : Replace failed disk 15c.42.2 with onsite spare.",
    "Date Open": "44038.53820601852",
    "Issue": "Data Drive Failure",
    "RMA Number": "N/A",
    "Work Order": "WO000194542",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Rishav Kumar",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "ST",
    "Vendor": "Silver Peak",
    "Group": "iCloud_Mail",
    "Hostname": "st14p37im-wam004",
    "Nagios Status": "production",
    "Warranty": "YES",
    "Priority": "restricted",
    "Ticket Number": "",
    "Ticket Title": "iTicket- : Failed disk on slot 5 on st14p37im-wam004 Please use RMA drive",
    "Date Open": "44037.18056712963",
    "Issue": "Data Drive Failure",
    "RMA Number": "need_RMA",
    "Work Order": "restricted",
    "WO Status": "restricted",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Anil Kumar Rajak",
    "Request By": "need_tracking",
    "Incoming Tracking": "need_tracking",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "PV",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "pv43p51im-filerm51001",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075996991",
    "Ticket Title": "iTicket- : Console ports are not reachable for the listed filers in DH 6200",
    "Date Open": "44030.633356481485",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191705",
    "WO Status": "Work",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "PV",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "pv42p36im-filerm36002",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075996980",
    "Ticket Title": "iTicket- : Console ports are not reachable for the listed filers in DH 4400",
    "Date Open": "44030.63196759259",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191704",
    "WO Status": "Work",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "PV",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "pv41p18im-filerm18561",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075996974",
    "Ticket Title": "iTicket- : Console ports are not reachable for the listed filers in DH 4200",
    "Date Open": "44030.63056712963",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191703",
    "WO Status": "Work",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "PV",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "pv36p39im-filerm39511",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075996962",
    "Ticket Title": "iTicket- : Console ports are not reachable for the listed filers in DH 3400",
    "Date Open": "44030.62849537037",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191701",
    "WO Status": "Work",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "PV",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "pv38p41im-filerm41511",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075996944",
    "Ticket Title": "iTicket- : Console ports are not reachable for the listed filers in DH 1400",
    "Date Open": "44030.62641203704",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191699",
    "WO Status": "Work",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "PV",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "pv37p45im-filerm45511",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075996910",
    "Ticket Title": "iTicket- : Console ports are not reachable for the listed filers in DH 1200",
    "Date Open": "44030.62362268518",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191698",
    "WO Status": "Work",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "NK",
    "Vendor": "NetApp",
    "Group": "SWU",
    "Hostname": "nk11p01su-filer001",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075994905",
    "Ticket Title": "iTicket- : Console port is not reachable for the listed filers in DH 0118",
    "Date Open": "44030.28891203704",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191639",
    "WO Status": "Work",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MS",
    "Vendor": "NetApp",
    "Group": "WWW",
    "Hostname": "ms11p01ww-filer001",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "3",
    "Ticket Number": "INC075994869",
    "Ticket Title": "iTicket- : Console port is not accessible for the listed filers in DH 1100",
    "Date Open": "44030.28475694444",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191638",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MS",
    "Vendor": "NetApp",
    "Group": "AMP",
    "Hostname": "ms11p00it-filer001",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075994855",
    "Ticket Title": "iTicket- : Console port is not reachable in DH 1100",
    "Date Open": "44030.28056712963",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191637",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "PV",
    "Vendor": "NetApp",
    "Group": "AMP",
    "Hostname": "pv39p00it-filer001",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075994829",
    "Ticket Title": "iTicket- : Console ports are not reachable for the listed filers in DH 2200",
    "Date Open": "44030.27570601852",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191636",
    "WO Status": "Work",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MR",
    "Vendor": "NetApp",
    "Group": "AMP",
    "Hostname": "mr24p00it-snapvault001",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075994783",
    "Ticket Title": "iTicket- : Console port is not reachable for mr24p00it-snapvault001",
    "Date Open": "44030.2722337963",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191635",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MR",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "Listed in attachment",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075992889",
    "Ticket Title": "iTicket- : Console Ports are not reachable for the listed filers in DH 0004 0405 0505 0803",
    "Date Open": "44030.05488425926",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191587",
    "WO Status": "Work",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "NK",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "Listed in attachment",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "3",
    "Ticket Number": "INC075992677",
    "Ticket Title": "iTicket- : Console Ports are not reachable for the listed filers in DH 0118",
    "Date Open": "44030.034050925926",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191583",
    "WO Status": "Pending Validation",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "ST",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "Listed in attachment",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075992407",
    "Ticket Title": "iTicket- : Console Ports are not reachable for the listed filers in DH 2000",
    "Date Open": "44030.00417824074",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191576|||||WO000194289",
    "WO Status": "Work",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "ST",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "Listed in attachment",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075992344",
    "Ticket Title": "iTicket- : Console Ports are not reachable for the listed filers in DH 0204",
    "Date Open": "44029.99863425926",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191574",
    "WO Status": "Work",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "ST",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "Listed in attachment",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075992332",
    "Ticket Title": "iTicket- : Console Ports are not reachable for the listed filers in DH 0201",
    "Date Open": "44029.99653935185",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191573",
    "WO Status": "Work",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "ST",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "Attached",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075991846",
    "Ticket Title": "iTicket- : Console Ports are not reachable for the listed filers in DH 101",
    "Date Open": "44029.943078703705",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000191565",
    "WO Status": "Work",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Praveen Malneedi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MR",
    "Vendor": "ZFSSA",
    "Group": "iCloud_Mail",
    "Hostname": "mr28p48im-gigaoverflow002",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075856601",
    "Ticket Title": "iTicket- : Replace faulty disk-01 on chassis-001 on mr28p48im-gigaoverflow002 with onsite spare",
    "Date Open": "44015.73405092592",
    "Issue": "Data Drive Failure",
    "RMA Number": "N/A",
    "Work Order": "WO000186529",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Rishav Kumar",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MS",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "ms11q41im-qugi24052401",
    "Nagios Status": "Staging",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075653259",
    "Ticket Title": "iTicket- : Need to Power cycle the host ms11q41im-qugi24052401",
    "Date Open": "43994.00417824074",
    "Issue": "Host Unreachable",
    "RMA Number": "N/A",
    "Work Order": "WO000180208",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Umakant Tripathi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "PV",
    "Vendor": "Isilon",
    "Group": "iCloud_Mail",
    "Hostname": "pv43p53im-wam004",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075581470",
    "Ticket Title": "iTicket: pv43p53im-wam004 went down , please do visual inspection",
    "Date Open": "43986.676412037035",
    "Issue": "Inspect Device",
    "RMA Number": "N/A",
    "Work Order": "WO000179367|||||WO000177916",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Kavitha Paulraj",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MR",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "mr36p72im-hyfp09030101",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075511311",
    "Ticket Title": "iTicket- : not able accès through IPMI mr36p72im-hyfp09030101",
    "Date Open": "43978.86599537037",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000175907",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Umakant Tripathi",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MS",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "ms12p71im-ztdj19293201",
    "Nagios Status": "Staging",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075325303",
    "Ticket Title": "iTicket- : Faulty Motherboard on ms12p71im-ztdj19293201",
    "Date Open": "43957.99585648148",
    "Issue": "Root Drive Failure",
    "RMA Number": "N/A",
    "Work Order": "WO000170759",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GDCS Ops",
    "Escalate": "Keerthi Puchakayala",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MS",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "ms12p71im-ztdj20292201",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075279432",
    "Ticket Title": "iTicket- : Not able to ping OOB on ms12p71im-ztdj20292201. Please do visual check",
    "Date Open": "43952.51530092592",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000168498",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Rishav Kumar",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MS",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "ms12p71im-ztdj19281901",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075278972",
    "Ticket Title": "iTicket- : Not able to ping OOB on ms12p71im-ztdj19281901.me.com. Please do visual check",
    "Date Open": "43952.4403125",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000168483",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "Vinodkumar Chirumamilla",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MR",
    "Vendor": "Mapr",
    "Group": "iCloud_Mail",
    "Hostname": "mr36p72im-hyfp09043301",
    "Nagios Status": "production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075268528",
    "Ticket Title": "iTicket- : Not able to ping OOB on mr36p72im-hyfp09043301.Please do visual check",
    "Date Open": "43951.147939814815",
    "Issue": "OOB network failure",
    "RMA Number": "N/A",
    "Work Order": "WO000168090",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "GIO-IS-Storage",
    "Escalate": "vignesh komarasamy",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "MS",
    "Vendor": "NetApp",
    "Group": "iCloud_Mail",
    "Hostname": "ms11q11im-filerm01102",
    "Nagios Status": "non-production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC075171421",
    "Ticket Title": "iTicket- : Environment system is busy on filer ms11q11im-filerm01102. Please do visual inspection on it.",
    "Date Open": "43941.54238425926",
    "Issue": "Power Supply Failure",
    "RMA Number": "N/A",
    "Work Order": "WO000190605|||||WO000168178",
    "WO Status": "Pending WorkOrder",
    "Ticket Status": "ISG Mail Storage",
    "Escalate": "Vinodkumar Chirumamilla",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  },
  {
    "DC": "ST",
    "Vendor": "Isilon",
    "Group": "iCloud",
    "Hostname": "st11a00is-isilon01",
    "Nagios Status": "non-production",
    "Warranty": "NO",
    "Priority": "2",
    "Ticket Number": "INC073681532",
    "Ticket Title": "iTicket- : Power Down Isilon Cluster st11a00is-isilon01",
    "Date Open": "43784.76945601852",
    "Issue": "Decommission",
    "RMA Number": "N/A",
    "Work Order": "NONE",
    "WO Status": "Work",
    "Ticket Status": "ISG Mail Storage",
    "Escalate": "Pacada",
    "Request By": "N/A",
    "Incoming Tracking": "N/A",
    "Outgoing Tracking": "N/A",
  }
 ]